---
name: Setup Node and Restore Cache

description: setup Node.js and save or restore npm_modules

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: "24"
        registry-url: "https://registry.npmjs.org"
        cache-dependency-path: "./package-lock.json"
