import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { writeGeneratedFile } from "../../../ops/helpers/generatedFiles.js";
import { formatGeneratedContents } from "../../../ops/helpers/generatedFormatting.js";
import { readSnapshot } from "../../all-named-html-entities/scripts/source.js";

const args = process.argv.slice(2);
if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
  throw new Error("Usage: node scripts/generate.js [--check]");
}
const mode = args.includes("--check") ? "check" : "write";
const readPolicy = (name) =>
  JSON.parse(
    readFileSync(new URL(`../policy/${name}.json`, import.meta.url), "utf8"),
  );
const names = readPolicy("names");
const aliases = readPolicy("named-replacements");
const { entities, notice } = readSnapshot();
if (
  new Set(names).size !== names.length ||
  names.some((name) => !Object.hasOwn(entities, `&${name};`)) ||
  Object.keys(aliases).some((name) => !names.includes(name))
) {
  throw new Error(
    "Email compatibility policy contains duplicate or unknown names",
  );
}
const replacements = {};
for (const name of names) {
  const row = entities[`&${name};`];
  if (Object.hasOwn(aliases, name)) {
    if (entities[`&${aliases[name]};`]?.characters !== row.characters) {
      throw new Error(`Email replacement alias changes the value of ${name}`);
    }
    replacements[name] = aliases[name];
  } else {
    // The public payload is wrapped once in & and ; by callers. Join all
    // Unicode code points with the delimiters of the intervening references.
    replacements[name] = row.codepoints
      .map((point) => `#x${point.toString(16).toUpperCase()}`)
      .join(";&");
  }
}
const lower = [...new Set(names.map((name) => name.toLowerCase()))].sort();
const outputs = {
  "notEmailFriendly.json": JSON.stringify(replacements, null, 2),
  "generated.ts": `${notice}// Generated by npm run generate; edit policy/ inputs instead.
export const notEmailFriendlySetOnly = /* @__PURE__ */ new Set(${JSON.stringify(names)});
export const notEmailFriendlyLowercaseSetOnly = /* @__PURE__ */ new Set(${JSON.stringify(lower)});
export const notEmailFriendlyMinLength = ${Math.min(...names.map((name) => name.length))};
export const notEmailFriendlyMaxLength = ${Math.max(...names.map((name) => name.length))};
`,
};
for (const [name, contents] of Object.entries(outputs)) {
  const filename = fileURLToPath(new URL(`../src/${name}`, import.meta.url));
  await writeGeneratedFile({
    contents: formatGeneratedContents({
      contents,
      filename,
      repositoryRoot: fileURLToPath(new URL("../../../", import.meta.url)),
    }),
    filename,
    fixCommand: "npm run generate --workspace html-entities-not-email-friendly",
    mode,
  });
}
console.log(
  `Email entity data ${mode === "check" ? "are current" : "generated"}.`,
);
