import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { writeGeneratedFile } from "../../../ops/helpers/generatedFiles.js";
import { formatGeneratedContents } from "../../../ops/helpers/generatedFormatting.js";

const args = process.argv.slice(2);
if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
  throw new Error("Usage: node scripts/generate.js [--check]");
}
const mode = args.includes("--check") ? "check" : "write";
const source = new URL("../src/", import.meta.url);
const all = Object.keys(
  JSON.parse(readFileSync(new URL("allNamedEntities.json", source), "utf8")),
);
const lower = [...new Set(all.map((name) => name.toLowerCase()))];

function affixes(names, end) {
  const result = {};
  for (const name of names) {
    const first = name[end ? name.length - 1 : 0];
    const second = name[end ? name.length - 2 : 1];
    result[first] ??= {};
    result[first][second] ??= [];
    result[first][second].push(name);
  }
  return result;
}

const outputs = {
  "startsWith.json": JSON.stringify(affixes(all, false), null, 2),
  "endsWith.json": JSON.stringify(affixes(all, true), null, 2),
  "startsWithCaseInsensitive.json": JSON.stringify(
    affixes(lower, false),
    null,
    2,
  ),
  "endsWithCaseInsensitive.json": JSON.stringify(affixes(lower, true), null, 2),
  "generated.ts": `// Generated by npm run generate; edit allNamedEntities.json instead.
export const allNamedEntitiesSetOnly = /* @__PURE__ */ new Set(${JSON.stringify(all)});
export const allNamedEntitiesSetOnlyCaseInsensitive = /* @__PURE__ */ new Set(${JSON.stringify(lower)});
export const minLength = ${Math.min(...all.map((name) => name.length))};
export const maxLength = ${Math.max(...all.map((name) => name.length))};
`,
};

for (const [name, contents] of Object.entries(outputs)) {
  const filename = fileURLToPath(new URL(name, source));
  await writeGeneratedFile({
    contents: formatGeneratedContents({
      contents,
      filename,
      repositoryRoot: fileURLToPath(new URL("../../../", import.meta.url)),
    }),
    filename,
    fixCommand: "npm run generate --workspace all-named-html-entities",
    mode,
  });
}
console.log(
  `Entity indexes ${mode === "check" ? "are current" : "generated"}.`,
);
