import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { writeGeneratedFile } from "../../../ops/helpers/generatedFiles.js";
import { formatGeneratedContents } from "../../../ops/helpers/generatedFormatting.js";
import { readSnapshot } from "./source.js";

const args = process.argv.slice(2);
if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
  throw new Error("Usage: node scripts/generate.js [--check]");
}
const mode = args.includes("--check") ? "check" : "write";
const source = new URL("../src/", import.meta.url);
const { entities, canonical, notice } = readSnapshot();
// Set and affix iteration order is part of the existing data product.
const all = JSON.parse(
  readFileSync(
    new URL("../upstream/public-name-order.json", import.meta.url),
    "utf8",
  ),
);
if (
  all.length !== canonical.length ||
  new Set(all).size !== all.length ||
  all.some((name) => !Object.hasOwn(entities, `&${name};`))
) {
  throw new Error(
    "Public entity order does not match the complete canonical table",
  );
}
const lower = [...new Set(all.map((name) => name.toLowerCase()))];
const namedReferencePrefixes = {};
for (const [name] of canonical) {
  namedReferencePrefixes[name.slice(1, 3)] ??= [];
}
for (const name of Object.keys(entities)) {
  if (!name.endsWith(";")) {
    namedReferencePrefixes[name.slice(1, 3)].push(name.slice(1));
  }
}
for (const names of Object.values(namedReferencePrefixes)) {
  names.sort((a, b) => b.length - a.length || (a < b ? -1 : a > b ? 1 : 0));
}

// Preserve invisible characters and UTF-16 pairs literally through formatting.
function asciiJson(value, indent) {
  return JSON.stringify(value, null, indent).replace(
    /[\u007f-\uffff]/g,
    (char) =>
      `\\u${char.charCodeAt(0).toString(16).toUpperCase().padStart(4, "0")}`,
  );
}

function affixes(names, end) {
  const result = {};
  for (const name of names) {
    const first = name[end ? name.length - 1 : 0];
    const second = name[end ? name.length - 2 : 1];
    result[first] ??= {};
    result[first][second] ??= [];
    result[first][second].push(name);
  }
  return result;
}

const outputs = {
  "allNamedEntities.json": asciiJson(
    Object.fromEntries(
      all.map((name) => [name, entities[`&${name};`].characters]),
    ),
    2,
  ),
  "startsWith.json": JSON.stringify(affixes(all, false), null, 2),
  "endsWith.json": JSON.stringify(affixes(all, true), null, 2),
  "startsWithCaseInsensitive.json": JSON.stringify(
    affixes(lower, false),
    null,
    2,
  ),
  "endsWithCaseInsensitive.json": JSON.stringify(affixes(lower, true), null, 2),
  "generated.ts": `${notice}// Generated by npm run generate from upstream/entities.json.
export const allNamedEntitiesSetOnly = /* @__PURE__ */ new Set(${JSON.stringify(all)});
export const allNamedEntitiesSetOnlyCaseInsensitive = /* @__PURE__ */ new Set(${JSON.stringify(lower)});
export const minLength = ${Math.min(...all.map((name) => name.length))};
export const maxLength = ${Math.max(...all.map((name) => name.length))};
`,
  "../../html-entity-codec/src/generated.ts": `${notice}// Generated by all-named-html-entities/scripts/generate.js; do not edit.
export const namedReferences: Record<string, string> = ${asciiJson(Object.fromEntries(Object.entries(entities).map(([name, row]) => [name.slice(1), row.characters])))};
export const maxNamedReferenceLength = ${Math.max(...Object.keys(entities).map((name) => name.length - 1))};
export const maxLegacyReferenceLength = ${Math.max(
    ...Object.keys(entities)
      .filter((name) => !name.endsWith(";"))
      .map((name) => name.length - 1),
  )};
export const namedReferencePrefixes: Record<string, string[]> = ${JSON.stringify(namedReferencePrefixes)};
`,
};

for (const [name, contents] of Object.entries(outputs)) {
  const filename = fileURLToPath(new URL(name, source));
  await writeGeneratedFile({
    contents: formatGeneratedContents({
      contents,
      filename,
      repositoryRoot: fileURLToPath(new URL("../../../", import.meta.url)),
    }),
    filename,
    fixCommand: "npm run generate --workspace all-named-html-entities",
    mode,
  });
}
console.log(
  `Entity indexes ${mode === "check" ? "are current" : "generated"}.`,
);
