[package]
name = "json-sort-cli-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
log = "0.4.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
